(function(factory){if(typeof define==='function'&&define.amd){define(['jquery'],factory);}else if(typeof module==='object'&&module.exports){module.exports=function(root,jQuery){if(jQuery===undefined){if(typeof window!=='undefined'){jQuery=require('jquery');}
else{jQuery=require('jquery')(root);}}
factory(jQuery);return jQuery;};}else{factory(jQuery);}}(function($){$.jGrowl=function(m,o){if($('#jGrowl').length===0)
$('<div id="jGrowl"></div>').addClass((o&&o.position)?o.position:$.jGrowl.defaults.position).appendTo((o&&o.appendTo)?o.appendTo:$.jGrowl.defaults.appendTo);$('#jGrowl').jGrowl(m,o);};$.fn.jGrowl=function(m,o){if(o===undefined&&$.isPlainObject(m)){o=m;m=o.message;}
if($.isFunction(this.each)){var args=arguments;return this.each(function(){if($(this).data('jGrowl.instance')===undefined){$(this).data('jGrowl.instance',$.extend(new $.fn.jGrowl(),{notifications:[],element:null,interval:null}));$(this).data('jGrowl.instance').startup(this);}
if($.isFunction($(this).data('jGrowl.instance')[m])){$(this).data('jGrowl.instance')[m].apply($(this).data('jGrowl.instance'),$.makeArray(args).slice(1));}else{$(this).data('jGrowl.instance').create(m,o);}});}};$.extend($.fn.jGrowl.prototype,{defaults:{pool:0,header:'',group:'',sticky:false,position:'top-right',appendTo:'body',glue:'after',theme:'default',themeState:'highlight',corners:'10px',check:250,life:3000,closeDuration:'normal',openDuration:'normal',easing:'swing',closer:true,closeTemplate:'&times;',closerTemplate:'<div>[ close all ]</div>',log:function(){},beforeOpen:function(){},afterOpen:function(){},open:function(){},beforeClose:function(){},close:function(){},click:function(){},animateOpen:{opacity:'show'},animateClose:{opacity:'hide'}},notifications:[],element:null,interval:null,create:function(message,options){var o=$.extend({},this.defaults,options);if(typeof o.speed!=='undefined'){o.openDuration=o.speed;o.closeDuration=o.speed;}
this.notifications.push({message:message,options:o});o.log.apply(this.element,[this.element,message,o]);},render:function(n){var self=this;var message=n.message;var o=n.options;o.themeState=(o.themeState==='')?'':'ui-state-'+o.themeState;var notification=$('<div/>').addClass('jGrowl-notification alert '+o.themeState+' ui-corner-all'+((o.group!==undefined&&o.group!=='')?' '+o.group:'')).append($('<button/>').addClass('jGrowl-close').html(o.closeTemplate)).append($('<div/>').addClass('jGrowl-header').html(o.header)).append($('<div/>').addClass('jGrowl-message').html(message)).data("jGrowl",o).addClass(o.theme).children('.jGrowl-close').bind("click.jGrowl",function(){$(this).parent().trigger('jGrowl.beforeClose');return false;}).parent();$(notification).bind("mouseover.jGrowl",function(){$('.jGrowl-notification',self.element).data("jGrowl.pause",true);}).bind("mouseout.jGrowl",function(){$('.jGrowl-notification',self.element).data("jGrowl.pause",false);}).bind('jGrowl.beforeOpen',function(){if(o.beforeOpen.apply(notification,[notification,message,o,self.element])!==false){$(this).trigger('jGrowl.open');}}).bind('jGrowl.open',function(){if(o.open.apply(notification,[notification,message,o,self.element])!==false){if(o.glue=='after'){$('.jGrowl-notification:last',self.element).after(notification);}else{$('.jGrowl-notification:first',self.element).before(notification);}
$(this).animate(o.animateOpen,o.openDuration,o.easing,function(){if($.support.opacity===false)
this.style.removeAttribute('filter');if($(this).data("jGrowl")!==null&&typeof $(this).data("jGrowl")!=='undefined')
$(this).data("jGrowl").created=new Date();$(this).trigger('jGrowl.afterOpen');});}}).bind('jGrowl.afterOpen',function(){o.afterOpen.apply(notification,[notification,message,o,self.element]);}).bind('click',function(){o.click.apply(notification,[notification,message,o,self.element]);}).bind('jGrowl.beforeClose',function(){if(o.beforeClose.apply(notification,[notification,message,o,self.element])!==false)
$(this).trigger('jGrowl.close');}).bind('jGrowl.close',function(){$(this).data('jGrowl.pause',true);$(this).animate(o.animateClose,o.closeDuration,o.easing,function(){if($.isFunction(o.close)){if(o.close.apply(notification,[notification,message,o,self.element])!==false)
$(this).remove();}else{$(this).remove();}});}).trigger('jGrowl.beforeOpen');if(o.corners!==''&&$.fn.corner!==undefined)$(notification).corner(o.corners);if($('.jGrowl-notification:parent',self.element).length>1&&$('.jGrowl-closer',self.element).length===0&&this.defaults.closer!==false){$(o.closerTemplate).addClass('jGrowl-closer '+this.defaults.themeState+' ui-corner-all').addClass(this.defaults.theme).appendTo(self.element).animate(this.defaults.animateOpen,this.defaults.speed,this.defaults.easing).bind("click.jGrowl",function(){$(this).siblings().trigger("jGrowl.beforeClose");if($.isFunction(self.defaults.closer)){self.defaults.closer.apply($(this).parent()[0],[$(this).parent()[0]]);}});}},update:function(){$(this.element).find('.jGrowl-notification:parent').each(function(){if($(this).data("jGrowl")!==undefined&&$(this).data("jGrowl").created!==undefined&&($(this).data("jGrowl").created.getTime()+parseInt($(this).data("jGrowl").life,10))<(new Date()).getTime()&&$(this).data("jGrowl").sticky!==true&&($(this).data("jGrowl.pause")===undefined||$(this).data("jGrowl.pause")!==true)){$(this).trigger('jGrowl.beforeClose');}});if(this.notifications.length>0&&(this.defaults.pool===0||$(this.element).find('.jGrowl-notification:parent').length<this.defaults.pool))
this.render(this.notifications.shift());if($(this.element).find('.jGrowl-notification:parent').length<2){$(this.element).find('.jGrowl-closer').animate(this.defaults.animateClose,this.defaults.speed,this.defaults.easing,function(){$(this).remove();});}},startup:function(e){this.element=$(e).addClass('jGrowl').append('<div class="jGrowl-notification"></div>');this.interval=setInterval(function(){var instance=$(e).data('jGrowl.instance');if(undefined!==instance){try{instance.update();}catch(e){instance.shutdown();throw e;}}},parseInt(this.defaults.check,10));},shutdown:function(){try{$(this.element).removeClass('jGrowl').find('.jGrowl-notification').trigger('jGrowl.close').parent().empty();}catch(e){throw e;}finally{clearInterval(this.interval);}},close:function(){$(this.element).find('.jGrowl-notification').each(function(){$(this).trigger('jGrowl.beforeClose');});}});$.jGrowl.defaults=$.fn.jGrowl.prototype.defaults;}));